name: Bygg og deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
env:
  sanityToken: ${{ secrets.SANITY_API_TOKEN }}
jobs:
  buildDev:
    uses: navikt/aap-workflows/.github/workflows/frontend-next-build.yml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      appname: 'aap-regelverk'
      playwright: false
      cdn: false
      appsecrets: SANITY_API_TOKEN

  deployDev:
    needs: buildDev
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      manifest: .nais/nais.yaml
      imageSuffix: -dev-gcp
      vars: .nais/dev.yaml
